version: '3'
services:
  web:
    platform: linux/x86_64
    build: ./
    ports:
      - "8069:8069"
    volumes:
      - ./addons:/mnt/extra-addons
    depends_on:
      - postgresql

  postgresql:
    platform: linux/x86_64
    image: postgres:16.2
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo16
      - POSTGRES_USER=odoo16
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data/pgdata
    restart: always