version: '3'
services:
  web:
    platform: linux/x86_64
    build: ./
    depends_on:
      - postgresql
    links:
      - postgresql
    ports:
      - "8069:8069"
    volumes:
      - ./docker-data/odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons-customize
    environment:
      - VIRTUAL_HOST=odoo15.marlonfalcon.com
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf --dev all"
    restart: always
  postgresql:
    platform: linux/x86_64
    image: postgres:16.2
    environment:
      - POSTGRES_DB=odoo
      - POSTGRES_PASSWORD=odoo16
      - POSTGRES_USER=odoo16
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./docker-data/db:/var/lib/postgresql/data/pgdata
    restart: always